Implementing gym leader / e4 only type theming mode, plus some ui sup…
Ajarmar/universal-pokemon-randomizer-zx pull request #375
Opened 2022-01-20 14:09 UTC by VoidModer

This is a cleaned up version of something I implemented for a customized nuzlocke run. It changes 2 main things:

1. Added a new trainer randomization mode that would apply type themes, but only for gym leaders & elite 4 members.
2. Converted the TrainersMod radio buttons to a ComboBox so stuff would fit on the page.

I've done a fair amount of bug testing across different rom versions and configurations, checking the log files for this and other modes to make sure they behaved appropriately, but I don't really know the project well enough to be confident that I hit everything important. 

Lmk if you have any questions. Thanks!

2022-01-20 14:16 UTC, VoidModer commented
Here's some screenshots of the UI change that I forgot to attach in the initial post.

![randomizer1](https://user-images.githubusercontent.com/45549015/150355426-e8b1bacd-db2c-4787-aa54-56c054f1c220.PNG)
![randomizer2](https://user-images.githubusercontent.com/45549015/150355461-29d40e81-6445-4b10-acd1-a7d858a4698b.PNG)
e

2022-02-26 20:31 UTC, Ajarmar requested changes
Hi, thanks for the PR (and sorry for the late response). We're definitely interested in a setting like this. There are a few things I'd like to see changed before we merge this.

- The name of the setting (both as it's presented in the GUI and in the code) is a bit misleading; there are regular trainers (and champions) in the games that have type themes, so "shuffle type themes" doesn't properly convey what the setting does. A more literal description would be better, such as "Type Themed (Gyms/Elite Four Only)"
- Some implementation details, see below

2022-02-26 20:31 UTC, Ajarmar commented on src/com/dabomstew/pkrandom/Settings.java
> +
```suggestion

```

2022-04-29 21:50 UTC, Ajarmar commented
Closing due to inactivity.

2022-04-29 21:50 UTC, closed without merging

2022-06-18 13:39 UTC, Terra-B-Welch commented
Hate to be a gravedigger, but was any progress ever made on this setting? I'd love to see this in future versions of the randomizer.

2022-06-18 18:25 UTC, Ajarmar commented
> Hate to be a gravedigger, but was any progress ever made on this setting? I'd love to see this in future versions of the randomizer.

Yes, it was added in https://github.com/Ajarmar/universal-pokemon-randomizer-zx/commit/51db48c59f70dc6a69b7b16116e4558b0f2662f9 and will be part of the next release