Enforce Dual Type Option
Ajarmar/universal-pokemon-randomizer-zx pull request #379
Opened 2022-01-24 18:47 UTC by Corruption-Echoes

Adds a button to the type UI that enforces all randomized pokemon types to be dual types

2022-02-12 04:13 UTC, tom-overton requested changes
Hey, thanks for the pull request! Sorry for the delay in our response. We'd be happy to merge this so long as the following things are addressed:
1. A tooltip is added to this checkbox.
2. The checkbox is not enabled by default

You can see both of these in this panel on the IntelliJ GUI editor:
![image](https://user-images.githubusercontent.com/12245827/153696103-47078a0d-2f42-49e8-951a-5e8a7784e267.png)

Look at how other checkboxes in the GUI work, and feel free to ask questions if you need!

There's also one small little code thing that would be nice to change.

2022-02-12 04:13 UTC, tom-overton commented on src/com/dabomstew/pkrandom/newgui/NewRandomizerGUI.java
> +        ptIsDualTypeCheckBox.setVisible(true);
Could you move these up to be next to the `ptFollowMegaEvosCheckBox` block on line 1939?

2022-02-16 19:38 UTC, tom-overton requested changes
Thanks for fixing everything I pointed out! Just two more things, and then we can merge this; one of which I failed to notice last time, sorry!

2022-02-16 19:38 UTC, tom-overton commented on src/com/dabomstew/pkrandom/newgui/Bundle.properties
> +GUI.ptForceDualTypeCheckBox.toolTipText=Checking this will force all Pokemon to have 2 types when types are randomized
```suggestion
GUI.ptForceDualTypeCheckBox.toolTipText=Checking this will force all Pokemon to have two types when types are randomized
```

2022-02-16 19:38 UTC, tom-overton commented on src/com/dabomstew/pkrandom/newgui/NewRandomizerGUI.java
> +            ptIsDualTypeCheckBox.setEnabled(true);
This should probably be:
```suggestion
            ptIsDualTypeCheckBox.setEnabled(false);
```
With the current code, what happens is that when you initially load a ROM, the "Force Dual Types" checkbox is enabled, even though the Types radio button is "Unchanged"
![image](https://user-images.githubusercontent.com/12245827/154342325-a37756cd-2ba9-47b6-9f67-738445e3af16.png)

2022-02-16 19:42 UTC, Corruption-Echoes commented
Fixed :)

2022-02-16 19:45 UTC, tom-overton approved these changes
Looks great, thanks for the quick fixes! When Ajarmar approves, we can merge it.

2022-02-16 19:52 UTC, Corruption-Echoes commented
Awesome! Thanks for the help tom, I've got another idea I'll be putting an contribution idea together for soon!

2022-02-16 20:57 UTC, Ajarmar approved these changes
Looks good, thanks for the contribution

2022-02-16 20:58 UTC, merged