Implementation for Issue #422
Ajarmar/universal-pokemon-randomizer-zx pull request #462
Opened 2022-06-14 05:55 UTC by TricksterGuy

Let me know if there are any problems. I just used WeighDuplicatesTogether as a framework to implement this.

2022-06-14 21:30 UTC, TricksterGuy commented
The changes are made as requested.

2022-06-14 22:35 UTC, tom-overton requested changes
Thanks, just one last thing:

2022-06-14 22:40 UTC, TricksterGuy commented on src/com/dabomstew/pkrandom/Settings.java
> +        settings.setEnsureTwoAbilities(restoreState(data[51], 7));
snap forgot to remove that fixed!

2022-06-14 22:43 UTC, tom-overton approved these changes

2022-06-16 06:02 UTC, Ajarmar approved these changes
Looks good, I'll merge it. Thanks for the contribution!

2022-06-16 06:03 UTC, merged